### ISSUE TITLE
Erroneus 0.1.3 tar.gz

### ISSUE THREAD

**Issue by angelabad** [jorgebastida/django-dajaxice#11]
The django-dajaxice-0.1.3.tar.gz in Downloads section is erroneus, has no CHANGELOG, templates dir in dajaxice, and other miss files, also include *.egg-info invalid dir.

I have send you for email the corrected tar.gz or you can download it from:
- http://www.wikisend.com/download/682634/

for 15 days.

Please upload it!

Thanks for your work.

**Comment by jorgebastida** [comment]
Hi Angel!
As you know, there are some problems in django-dajaxice-0.1.3 concerning installation:
- No CHANGELOG
- No templates directory
- zip_safe unnecessary
  To solve all this important errors I will define a new version to ensure proper upgrade.
  Everything has been fixed in 0.1.4.

Sorry for the delay.
Thanks for your work too ;-)
