### ISSUE TITLE
Dajaxice should make use of autodiscover pattern

### ISSUE THREAD

**Issue by lukaszb** [jorgebastida/django-dajaxice#13]
Propose to use autodiscover pattern (similar to Django's admin) - this would allow other pluggable's to use dajaxice - having to configure ajaxed functions at project's level makes it a little bit harder.

**Comment by jorgebastida** [comment]
Currently I have a workaround to solve this issue.
I'm using a similar approach that django.contrib.admin uses. This patch will fix this issue (#13) and #6 because that functions could be registered wherever you want at any module depth.

That new implementation will be released as django-dajaxice-0.1.5

**Comment by jorgebastida** [comment]
Check the HEAD version, there is a new approach to register dajaxice functions that resolves this issue.
