### ISSUE TITLE
Is there a way to split ajax.py into a few smaller files?

### ISSUE THREAD

**Issue by alexyer** [jorgebastida/django-dajaxice#138]
Is there a way to split ajax.py into a few smaller files?
Thank you.

**Comment by markuz** [comment]
Since dajaxice look into ajax.py for functions with the @dajaxice_register decorator you can just "import" them, having your dajaxice decorated functions wherever you want.

ej. The easies way:

```
from project.module.views import *
```

With this you may need to add a check for models being imported redefined (specially if you use modelAdmin).

The clean way:

```
from project.module.views import decorated_function
```

Hope this help you.

**Comment by alexyer** [comment]
Thank you. I will try. And I've also found this pull request. May be it will help someone.
https://github.com/jorgebastida/django-dajaxice/pull/53
