### ISSUE TITLE
Problem with collectstatic

### ISSUE THREAD

**Issue by h3** [jorgebastida/django-dajaxice#66]
Whether I use collect static with the -l option or not, dajaxice creates symlink to a tmp file instead of copying dajaxice.core.js.

Now even if I add the option FollowSymLinks set on my static directory I get a 403 Forbidden error.

The temp file is created and valid, but I cannot get Apache to serve a symlink pointing to a file into /tmp/.

**Comment by h3** [comment]
I was wrong, when I use copy instead of symlinks it works. But it still annoying because I usually use symlinks because they are faster and more space efficient.

Also, I'm really not sure that static was the appropriate place to put that generated script .. That said this is not an easy problem and I don't have a simple answer to it.

What I'm sure though, is that symlinking any code into /tmp/ for a production project is probably not a good idea.

**Comment by jorgebastida** [comment]
For sure is not! The idea about collectstatic is to freeze all this assets into a folder and then serve them using nginx/apache/whatever.

The reason because dajaxice creates this file is because the file itself doesn't exists until is requested or somebody calls `collectstatic`.

My recommendation is to not use `--link` if you are using `dajaxice`.

**Comment by aztrock** [comment]
I call dajaxice.core.js collectstatic but is empty without any application which is already registered,
